#spring.application.name=schoolems
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/school_management
spring.datasource.username=postgres
spring.datasource.password=pelunmi
spring.datasource.driver-class-name=org.postgresql.Driver
spring.security.user.name=admin
spring.security.user.password=12345
spring.security.user.roles=ADMIN


#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# JWT Configuration
jwt.secret=2A8x!Tq7B#eX3LmZ9v!4PnC5QrT8zU1X
jwt.expiration=86400000
